#!/usr/bin/env node

/**
 * Theme Generator Script
 * 
 * Reads theme.json and generates:
 * - CSS variables in theme.css
 * - Updates index.html with branding metadata
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const THEME_PATH = join(__dirname, '../theme.json');
const CSS_DIR = join(__dirname, '../src/css');
const THEME_CSS_PATH = join(CSS_DIR, 'theme.css');

// Read theme.json
function loadTheme() {
    try {
        const themeData = readFileSync(THEME_PATH, 'utf8');
        return JSON.parse(themeData);
    } catch (error) {
        console.error('❌ Error reading theme.json:', error.message);
        process.exit(1);
    }
}

// Generate CSS variables from theme
function generateThemeCSS(theme) {
    const { colors, typography, spacing, borderRadius, shadows, transitions } = theme;

    const css = `/**
 * THEME VARIABLES
 * Auto-generated from theme.json
 * DO NOT EDIT THIS FILE MANUALLY
 * Run: npm run generate-theme
 */

:root {
  /* PRIMARY COLORS */
  --color-primary: ${colors.primary.main};
  --color-primary-light: ${colors.primary.light};
  --color-primary-dark: ${colors.primary.dark};
  --color-primary-contrast: ${colors.primary.contrast};

  /* SECONDARY COLORS */
  --color-secondary: ${colors.secondary.main};
  --color-secondary-light: ${colors.secondary.light};
  --color-secondary-dark: ${colors.secondary.dark};
  --color-secondary-contrast: ${colors.secondary.contrast};

  /* BACKGROUND COLORS */
  --color-bg-default: ${colors.background.default};
  --color-bg-paper: ${colors.background.paper};
  --color-bg-navbar: ${colors.background.navbar};
  --color-bg-overlay: ${colors.background.overlay};

  /* TEXT COLORS */
  --color-text-primary: ${colors.text.primary};
  --color-text-secondary: ${colors.text.secondary};
  --color-text-disabled: ${colors.text.disabled};
  --color-text-hint: ${colors.text.hint};

  /* STATUS COLORS */
  --color-success: ${colors.status.success};
  --color-warning: ${colors.status.warning};
  --color-error: ${colors.status.error};
  --color-info: ${colors.status.info};

  /* INTERACTIVE STATES */
  --color-hover: ${colors.interactive.hover};
  --color-selected: ${colors.interactive.selected};
  --color-disabled: ${colors.interactive.disabled};
  --color-focus: ${colors.interactive.focus};

  /* BORDERS */
  --color-border-light: ${colors.borders.light};
  --color-border-medium: ${colors.borders.medium};
  --color-border-dark: ${colors.borders.dark};

  /* SHADOWS */
  --shadow-sm: ${shadows.sm};
  --shadow-md: ${shadows.md};
  --shadow-lg: ${shadows.lg};
  --shadow-xl: ${shadows.xl};

  /* TYPOGRAPHY */
  --font-primary: ${typography.fontFamily.primary};
  --font-secondary: ${typography.fontFamily.secondary};
  --font-mono: ${typography.fontFamily.monospace};

  --font-size-xs: ${typography.fontSize.xs};
  --font-size-sm: ${typography.fontSize.sm};
  --font-size-base: ${typography.fontSize.base};
  --font-size-lg: ${typography.fontSize.lg};
  --font-size-xl: ${typography.fontSize.xl};
  --font-size-2xl: ${typography.fontSize['2xl']};
  --font-size-3xl: ${typography.fontSize['3xl']};

  --font-weight-light: ${typography.fontWeight.light};
  --font-weight-normal: ${typography.fontWeight.normal};
  --font-weight-medium: ${typography.fontWeight.medium};
  --font-weight-semibold: ${typography.fontWeight.semibold};
  --font-weight-bold: ${typography.fontWeight.bold};

  /* SPACING */
  --spacing-xs: ${spacing.xs};
  --spacing-sm: ${spacing.sm};
  --spacing-md: ${spacing.md};
  --spacing-lg: ${spacing.lg};
  --spacing-xl: ${spacing.xl};
  --spacing-2xl: ${spacing['2xl']};

  /* BORDER RADIUS */
  --radius-sm: ${borderRadius.sm};
  --radius-md: ${borderRadius.md};
  --radius-lg: ${borderRadius.lg};
  --radius-full: ${borderRadius.full};

  /* TRANSITIONS */
  --transition-fast: ${transitions.fast};
  --transition-base: ${transitions.base};
  --transition-slow: ${transitions.slow};
}

/* BODY DEFAULTS */
body {
  font-family: var(--font-primary);
  font-size: var(--font-size-base);
  color: var(--color-text-primary);
  background-color: var(--color-bg-default);
}
`;

    return css;
}

// Write theme.css
function writeThemeCSS(css) {
    try {
        writeFileSync(THEME_CSS_PATH, css, 'utf8');
        console.log('✅ Generated theme.css');
    } catch (error) {
        console.error('❌ Error writing theme.css:', error.message);
        process.exit(1);
    }
}

// Main execution
function main() {
    console.log('🎨 Generating theme...\n');

    const theme = loadTheme();
    console.log(`📋 Loaded theme: ${theme.branding.restaurantName}`);

    const themeCSS = generateThemeCSS(theme);
    writeThemeCSS(themeCSS);

    console.log('\n✨ Theme generation complete!');
}

main();
